// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnfdzwjchceumpzhkccl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZmR6d2pjaGNldW1wemhrY2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjA3OTksImV4cCI6MjA2NTMzNjc5OX0.vqh-KKDUIL21Uu8Misc4XEwTBk_yBVrV0b7YdCMRap8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);